spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wx_order?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true


  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# redis 配置
  redis:
    host: 120.79.185.188
    port: 6379
    password: 961122
#配置freemarker文件根路径
#  freemarker:
#    template-loader-path: /templates/

#logging:
#    pattern:
#        console: "%d - %msg%n"
##    path: E:/sell/log
#    file: E:/sell/log/sell.log
#    level: debug

wechat:
  mpAppId: wxb1242612bfa20990
  mpAppSecret: 07265d7922be29a7e50a472e2d2ff2db
  openAppId: xxx
  openAppSecret: xxx
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://scnf.natapp1.cc/sell/pay/notfiy
  templateId:
    orderStatus: xxx

url:
  sell: http://scnf.natapp1.cc
  wechatMpAuthorize: http://scnf.natapp1.cc
  wechatOpenAuthorize: http://scnf.natapp1.cc

server:
  servlet:
    context-path: /sell
