spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wx_order?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    default-property-inclusion: non_null

#logging:
#    pattern:
#        console: "%d - %msg%n"
##    path: E:/sell/log
#    file: E:/sell/log/sell.log
#    level: debug

wechat:
  mpAppId: wxb1242612bfa20990
  mpAppSecret: 07265d7922be29a7e50a472e2d2ff2db

url:
  sell: http://scnf.natapp1.cc
  wechatMpAuthorize: http://scnf.natapp1.cc

server:
  servlet:
    context-path: /sell